queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

steps:
- bash: |
    # login
    set -e
    echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

  displayName: Login to ACR Registry
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    set -e
    export CI_RUN=1
    export RUN_TESTS=1
    export namespace=$(namespace)
    export branch=$(branch)
    export tag=$(tag)
    chmod +x ./kudulite/build.sh
    ./kudulite/build.sh
  displayName: Build KuduLite Image
  continueOnError: false

- bash: |
    set -e
    export CI_RUN=1
    export RUN_TESTS=1
    export tag=$(tag)
    export storageAccountName=$(storageAccountName)
    export storageAccountKey=$(storageAccountKey)
    export v2RuntimeVersion=$(v2RuntimeVersion)
    export v3RuntimeVersion=$(v3RuntimeVersion)
    chmod +x ./kudulite/test.sh
    ./kudulite/test.sh
  displayName: Test KuduLite Image
  continueOnError: false

- bash: |
    set -e
    export CI_RUN=1
    export RUN_TESTS=1
    export tag=$(tag)
    chmod +x ./kudulite/publish.sh
    ./kudulite/publish.sh
  displayName: Publish KuduLite Image
  continueOnError: false