queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - dev
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/dotnet/*

trigger:
  branches:
    include:
      - refs/tags/3.0.*
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/dotnet/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin $(dockerRegistry)

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=$(dockerRegistry)/azure-functions/dotnet:3.0

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/dotnet/dotnet-inproc/dotnet.Dockerfile \
                  host/3.0/buster/amd64/dotnet/dotnet-inproc/
      npm run test $IMAGE_NAME --prefix test/
      docker push $IMAGE_NAME
    displayName: dotnet
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=$(dockerRegistry)/azure-functions/dotnet:3.0-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/dotnet/dotnet-inproc/dotnet-slim.Dockerfile \
                  host/3.0/buster/amd64/dotnet/dotnet-inproc/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: dotnet-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=$(dockerRegistry)/azure-functions/dotnet:3.0-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/dotnet/dotnet-inproc/dotnet-appservice.Dockerfile \
                  host/3.0/buster/amd64/dotnet/dotnet-inproc/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: dotnet-appservice
    continueOnError: false
